### PR TITLE
Added TRX Result Channel to write out a TRX Report

### PR DESCRIPTION
**Pull request by dotMorten**
Adds a TRX Report channel.
The output parses schema validation and opens cleanly in Visual Studio (for me at least :-) )

### CODE REVIEW

**Comment by dotMorten** [comment]
Isn't that a breaking change to rename?

**Comment by onovotny** [comment]
No because it wasn't public before :)

**Comment by dotMorten** [comment]
Why make it public though? To avoid the obsolete warning?

**Comment by onovotny** [comment]
Yeah, to give people the choice

**Comment by joaosilvareed** [comment]
Hi, I'm super interested in getting the trx report but I can't seem to find any documentation for this change, can someone please help on how to use this for example, in the AppDelegate?

Thanks.

**Pull request merged**
